import { motion } from 'framer-motion';
import { FaRobot, FaUserMd, FaBullseye, FaChartLine } from 'react-icons/fa';

const features = [
  {
    icon: <FaRobot className="w-12 h-12 md:w-14 md:h-14 text-mealr-pink" />,
    title: 'Endless Variety, Powered by AI',
    description: 'Tired of repetitive meal plans? Swipe through diverse meals tailored to your preferences and goals — all smartly generated by AI.',
  },
  {
    icon: <FaUserMd className="w-12 h-12 md:w-14 md:h-14 text-mealr-pink" />,
    title: 'Designed by Experts, Not Just Algorithms',
    description: "Every plan is crafted by certified nutritionists to ensure you're not just eating better — you're eating right.",
  },
  {
    icon: <FaBullseye className="w-12 h-12 md:w-14 md:h-14 text-mealr-pink" />,
    title: 'Tailored to Your Goals',
    description: "Whether you're losing fat, building muscle, or maintaining your weight, Mealr builds a plan that adapts with you.",
  },
  {
    icon: <FaChartLine className="w-12 h-12 md:w-14 md:h-14 text-mealr-pink" />,
    title: 'Real Flexibility for Real Life',
    description: 'Life changes — your meal plan should too. Swipe, swap, and adjust meals without ever falling off track.',
  },
];

const Features = () => {
  return (
    <section id="features" className="section bg-mealr-bg py-20">
      <div className="container">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
          className="text-center mb-16"
        >
          <h2 className="text-3xl md:text-4xl font-bold mb-4">Why Choose Mealr</h2>
          <p className="text-mealr-text-light text-lg max-w-2xl mx-auto">
            Mealr combines nutritionist-approved plans with real-time flexibility — helping you stay on track without eating the same thing twice.
          </p>
        </motion.div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          {features.map((feature, index) => (
            <motion.div
              key={index}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6, delay: index * 0.1 }}
              whileHover={{ y: -5 }}
              className="feature-card bg-white rounded-xl p-8 shadow-sm hover:shadow-lg transition-all duration-300"
            >
              <div className="flex flex-col items-center text-center">
                <motion.div
                  whileHover={{ scale: 1.1 }}
                  transition={{ duration: 0.2 }}
                >
                  {feature.icon}
                </motion.div>
                <h3 className="text-xl font-semibold mt-6 mb-3">{feature.title}</h3>
                <p className="text-mealr-text-light leading-relaxed">{feature.description}</p>
              </div>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default Features; 